#define SPLIT_ACTIVITY_ENABLE

#define SPLIT_TRANSACTION_IDS_USER KEY_POS_SYNC, TRACKPAD_POS_SYNC

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_TIME 100
#define AUTO_MOUSE_THRESHOLD 0
