#define SPLIT_ACTIVITY_ENABLE

#define SPLIT_TRANSACTION_IDS_USER KEY_POS_SYNC, TRACKPAD_POS_SYNC

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_TIME 250
#define AUTO_MOUSE_THRESHOLD 0

#define QUANTUM_PAINTER_NUM_FONTS 6
#define QUANTUM_PAINTER_NUM_IMAGES 12

// qmk-vim
#define BETTER_VISUAL_MODE
#define VIM_G_MOTIONS
#define VIM_PASTE_BEFORE
#define VIM_REPLACE
#define VIM_DOT_REPEAT
#define VIM_W_BEGINNING_OF_WORD
#define VIM_NUMBERED_JUMPS
