#include "quantum.h"

enum custom_keycodes {
    VIM_TOGGLE = QK_KB_0,
    GAMING_TOGGLE,
    RM_RESET,
    PC_LOCK,
    SENS_SHIFT,
    DPI_UP,
    DPI_DOWN,
    // Macro keycodes
    MACRO_REC_1,
    MACRO_REC_2,
    MACRO_REC_3,
    MACRO_REC_4,
    MACRO_REC_5,
    MACRO_REC_6,
    MACRO_REC_7,
    MACRO_REC_8,
    MACRO_REC_9,
    MACRO_REC_10,
    MACRO_PLAY_1,
    MACRO_PLAY_2,
    MACRO_PLAY_3,
    MACRO_PLAY_4,
    MACRO_PLAY_5,
    MACRO_PLAY_6,
    MACRO_PLAY_7,
    MACRO_PLAY_8,
    MACRO_PLAY_9,
    MACRO_PLAY_10,
    MACRO_STOP,
    MACRO_CLEAR_1,
    MACRO_CLEAR_2,
    MACRO_CLEAR_3,
    MACRO_CLEAR_4,
    MACRO_CLEAR_5,
    MACRO_CLEAR_6,
    MACRO_CLEAR_7,
    MACRO_CLEAR_8,
    MACRO_CLEAR_9,
    MACRO_CLEAR_10,
};

enum layers {
    _QWERTY = 0,
    _GAMING,
    _GAMING_UP,
    _SYM,
    _NAV,
    _NAV_UP,
    _FKEYS,
    _HUB,
    _MOUSE_KEYS,
    _MACROS,
};
